@startuml GraphBlock
state "GraphBlock" as Maze_StateFoundry_Editor_GraphBlock {
  state "Idle" as Maze_StateFoundry_Editor_GraphBlock_Idle {
  }
  state "Update" as Maze_StateFoundry_Editor_GraphBlock_Update {
    state "BlockEvaluation" as Maze_StateFoundry_Editor_GraphBlock_Update_BlockEvaluation {
    }
    state "Generation" as Maze_StateFoundry_Editor_GraphBlock_Update_Generation {
      state "HierarchyAnalysis" as Maze_StateFoundry_Editor_GraphBlock_Update_Generation_HierarchyAnalysis {
      }
      state "TextGeneration" as Maze_StateFoundry_Editor_GraphBlock_Update_Generation_TextGeneration {
      }
      state "UmlPrinting" as Maze_StateFoundry_Editor_GraphBlock_Update_Generation_UmlPrinting {
      }
    }
  }
  state "Error" as Maze_StateFoundry_Editor_GraphBlock_Error {
  }
}
Maze_StateFoundry_Editor_GraphBlock_Idle --> Maze_StateFoundry_Editor_GraphBlock_Update_BlockEvaluation : ScriptImported
Maze_StateFoundry_Editor_GraphBlock_Update_BlockEvaluation --> Maze_StateFoundry_Editor_GraphBlock_Idle : ScriptIsNotBlock
Maze_StateFoundry_Editor_GraphBlock_Update_BlockEvaluation --> Maze_StateFoundry_Editor_GraphBlock_Update_Generation_HierarchyAnalysis : ScriptIsBlock
Maze_StateFoundry_Editor_GraphBlock_Update --> Maze_StateFoundry_Editor_GraphBlock_Error : ErrorRaised
Maze_StateFoundry_Editor_GraphBlock_Error --> Maze_StateFoundry_Editor_GraphBlock_Idle : ErrorHandled
Maze_StateFoundry_Editor_GraphBlock_Update_Generation_HierarchyAnalysis --> Maze_StateFoundry_Editor_GraphBlock_Update_Generation_TextGeneration : HierarchyAnalyzed
Maze_StateFoundry_Editor_GraphBlock_Update_Generation_TextGeneration --> Maze_StateFoundry_Editor_GraphBlock_Update_Generation_UmlPrinting : TextGenerated
Maze_StateFoundry_Editor_GraphBlock_Update_Generation_UmlPrinting --> Maze_StateFoundry_Editor_GraphBlock_Idle : UmlPrinted
[*] --> Maze_StateFoundry_Editor_GraphBlock_Idle
@enduml
